In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
slice_of_array = arr[0:5]

In [5]:
slice_of_array

array([0, 1, 2, 3, 4])

In [6]:
slice_of_array[:] = 100

In [7]:
arr #It's affect the original array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
array_of_arr = arr.copy() #It's not affected the original one

In [9]:
array_of_arr[:] = 100

In [10]:
array_of_arr 

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])